export { directoriesFilesToIFile, fileToIFile, parseIFileToRecord } from './fileConvertors.ts'
export { normalizeText } from './normalizeText.ts'
export { vectorMagnitude } from './vectorMagnitude.ts'
export { computeTermFrequencies } from './computeTermFrequencies.ts'
export { buildTermMatrix } from './buildTermMatrix.ts'
