export { directoriesFilesToIFile, fileToIFile, parseIFileToRecord } from './fileConvertors.ts'
export { normalizeText } from './normalizeText.ts'
export { normalizeVector } from './normalizeVector.ts'
export { computeTermFrequencies } from './computeTermFrequencies.ts'
export { buildTermMatrix } from './buildTermMatrix.ts'
